### ISSUE TITLE
Add the "balance" command  to chat_commands

### ISSUE THREAD

**Issue by Chenterito** [Resxt/Plutonium-IW5-Scripts#2]
Add the "balance" command to self-balance the equipment when the user requires it.
What you need to run autobalancing:
`BalanceTeams()
{
    if ( !maps\mp\gametypes\_teams::getteambalance() )
            level maps\mp\gametypes\_teams::balanceteams();
}`

**Comment by Resxt** [comment]
Added. Thanks
https://github.com/Resxt/Plutonium-IW5-Scripts/commit/7a3e2e24908156cdfe63d400f68a8f8cf7cf9ec6
