### ISSUE TITLE
Support for upper and lower case commands.

### ISSUE THREAD

**Issue by Chenterito** [Resxt/Plutonium-IW5-Scripts#5]
I wanted to use the commands in capital letters and it didn't recognize.

**Comment by Resxt** [comment]
I don't really see why you would type like that but I added support for all casing for both command names and the "me" used for targeting yourself so you can now type `!KiLl mE` and it'll work
https://github.com/Resxt/Plutonium-IW5-Scripts/commit/e6bcab0960f675a733ceaf64919ac402c8c6ac79

If you find any bug/issue about this please DM me on Discord
