### ISSUE TITLE
[Support] CTF support for mapvote.gsc

### ISSUE THREAD

**Issue by Master-64** [Resxt/Plutonium-IW5-Scripts#8]
As specified in the readme for the project, it's clearly stated that CTF support wouldn't be added. However, I'd like to understand why exactly it isn't supported, as well as why it can't be easily fixed. I feel like a function override is all that would be needed, but I'm likely not thinking with enough depth to see why it's such an annoying issue. I've tried some fixes myself, but to no avail of course.

I would definitely be interested in seeing CTF getting officially supported, as my friends and I love CTF, but the most functional script for map voting (being this one) doesn't support it yet.

**Comment by Resxt** [comment]
I'm not working on this anymore and I couldn't make it work because of the amount of HUD elements already on screen (game/engine has limitations)

Probably need to destroy HUD elements such as flags before game ends
